buffer_size: 10000
batch_size: 512
gamma: 1.0
tau: 1e-2
learning_rate_actor: 1e-4
learning_rate_critic: 1e-4
weight_decay: 0
update_every: 1
data_dir: "data/"

actor_fc1_units: 75
actor_fc2_units: 60
critic_fc1_units: 75
critic_fc2_units: 60
