buffer_size: 100000
batch_size: 128
gamma: 0.99
tau: 1e-3
learning_rate_actor: 1e-4
learning_rate_critic: 1e-4
weight_decay: 0
update_every: 1
data_dir: "data/"

actor_fc1_units: 400
actor_fc2_units: 300
critic_fc1_units: 400
critic_fc2_units: 300
