"""Add model table

Revision ID: 50494450f2df
Revises: 286151c72898
Create Date: 2019-02-04 07:43:29.451608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50494450f2df'
down_revision = '286151c72898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_label', sa.String(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('model_config', sa.PickleType(), nullable=True),
    sa.Column('model_dict', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model')
    # ### end Alembic commands ###
