"""Add critic values

Revision ID: 5b209f371e20
Revises: 67428bb7f6db
Create Date: 2019-04-27 10:05:07.403462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b209f371e20'
down_revision = '67428bb7f6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criticinputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.PickleType(), nullable=True),
    sa.Column('actions', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criticvalues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_idx', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('input_id', sa.Integer(), nullable=True),
    sa.Column('value1', sa.Float(), nullable=True),
    sa.Column('value2', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['criticinputs.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('criticvalues')
    op.drop_table('criticinputs')
    # ### end Alembic commands ###
